#!/usr/bin/env bash

set -e

TARGET="$HOME"

Usage() {
  echo "Usage: $(basename $0)" [-d TARGET] PACKAGE
}

while getopts ":d:" OPTION; do
  case "$OPTION" in
    d)
      TARGET="$OPTARG"
      ;;
    ?)
      Usage
      exit 1
      ;;
  esac
done

shift "$(($OPTIND -1))"
PACKAGE=$1

if [ -z $PACKAGE ]; then
  Usage
  exit 1
fi

if [ -d $PACKAGE ]; then
  echo "  Stowing '$PACKAGE' to '$TARGET'"
  stow --no-folding --target=$TARGET --restow $PACKAGE
else
  echo "  Package '$PACKAGE' does not exist"
  exit 1
fi
