# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 0  # don't truncate path
truncate_to_repo = false  # don't truncate to git repo root
